### ISSUE TITLE
Missing fit_data files

### ISSUE THREAD

**Issue by luna983** [thimotei/CFR_calculation#13]
Country data files for the US, UK, etc. (essentially everything after T) are missing here: https://github.com/thimotei/CFR_calculation/tree/master/global_estimates/outputs/fit_data

Would it be possible to share those publicly as well? This is really great work, and we are using these estimates for policy effect analysis.

Much appreciated!

**Comment by thimotei** [comment]
Ah apologies, the master branch has become the branch on which we are still developing an extension to the model. The data and model used for the current online version are in the poisson_GAMs branch, which wasn't default until a second ago, but it now is. Apologies for this!

In this branch, we don't save the model fit datafiles, as they are very quick to run (the other branch is a fully bayesian model, so we save the MCMC outputs as they go, incase it crashes!). On the GAMs branch, you can run the full analysis for all countries (using main_script_temporal.R) and it runs all of it in roughly a minute (on a fairly standard Lenovo Thinkpad)

I hope that helps. The fully bayesian model with model fit files should be available later on today, as I am planning on running that version of the analysis too. Please let me know if there is anything else I can directly do

**Comment by luna983** [comment]
Thanks so much for the quick response! Got it, this is very helpful.
