### ISSUE TITLE
Bayesian inference of parameters

### ISSUE THREAD

**Issue by mohdibntarek** [thimotei/CFR_calculation#16]
Hi, 

Thanks for sharing this work. I am one of the developers of https://github.com/TuringLang/Turing.jl, a package for Bayesian inference in the Julia programming language. Have you considered running Bayesian inference on your model yet?

**Comment by thimotei** [comment]
Hi,

We've already begun development of a fully bayesian version of this analysis. We have been implementing it in the library called greta so far, which has been great (pardon the almost pun!). I'll take a look at Turing, and thanks for letting us know about it. Always good to be aware of what is out there! But I think for the moment we are fine using greta

Cheers!
Tim

**Comment by mohdibntarek** [comment]
I see. Thanks for your response and sorry for getting back late; the notification email drowned in my emails. Once you have the greta models, I will be happy to port them to Turing. In Turing, you have access to Stan's NUTS algorithm implemented in https://github.com/TuringLang/AdvancedHMC.jl. There is also Gibbs sampling for discrete parameters. Let me know if you give Turing a second thought :)
