### ISSUE TITLE
Absolute paths

### ISSUE THREAD

**Issue by seabbs** [thimotei/CFR_calculation#4]
Looking good Tim - just creeping here. New dev stuff looks good so far. 

A note on absolute paths (i.e `setwd("~/Documents/lshtm/github repos/CFR_calculation/global_estimates/")
if(grepl(Sys.info()["user"], pattern = "^adamkuchars(ki)?$")){setwd("~/Documents/GitHub/CFR_calculation/global_estimates/")}
`). There isn't really a need for these and they make it hard for non-auth users to use the code. 

An alternative with minimal set up is the `here` package. Wrap all paths in `here::here()` and make a `.here` file in the root directory. It will work just like this but for everyone. 

If interested and you would like me to implement then just let me know and I will submit a pull.

**Comment by thimotei** [comment]
Cheers Sam, sorry for late reply! Yes, I'm a big fan of the here::here() package and command. I've added it myself to both the Poisson_GAMS main script and the master branch main script. You're definitely right, it is way more reproducable this way

Cheers!
