### ISSUE TITLE
Use of Gams

### ISSUE THREAD

**Issue by seabbs** [thimotei/CFR_calculation#5]
I see some GAMs in the new code. A few comments (feel free to close after reading). 

* Have you checked the dimension of k is sufficient?  If not you should consider doing this
* I see you estimating normal CIs - do these match those created internally by `mgcv`. Why generate your own CIs? 
* You might enjoy using [`gratia`](https://gavinsimpson.github.io/gratia/) for exploring and plotting your GAMs.
* I am sure you have considered this but some kind of joint hierarchical estimation might make sense where you can test the temporal trend for differences between regions (GAMs all the way down of course). 

GIve me a ping if want to chat about this.

**Comment by thimotei** [comment]
Cheers Sam. We're in the middle of making the CFR calculation Bayesian at the same time as fitting GAMs to time-series of the under-reporting estimates. Still at the getting it all together and working stage. Shouldn't be much longer until its basically all in place. Once it is, I'll send you a message to chat about your suggestions
